spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
 
logging:
    level:
      org.springframework: INFO
      com.example: DEBUG
      
server:
    port: 8080

jwt:
  cookiename: cmoreno
  secretkey: o0xEXh3P*SX;mlZcT'Y)+Vd2p+}*V

